apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/akfnt/cns-edge-service/k8s?ref=d6b09c536ac21b4f054db4536b7377a31de8b3c4

patches:
- path: patch-env.yml
- path: patch-ingress.yml
- path: patch-volumes.yml
- path: patch-resources.yml

configMapGenerator:
- behavior: merge
  files:
  - application-prod.yml
  name: cns-edge-config

images:
- name: cns-edge-service
  newName: ghcr.io/akfnt/cns-edge-service
  newTag: 38a4fffe3deb25cca82c86b47ed370208128c72e

replicas:
- count: 1
  name: cns-edge-service
