apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/akfnt/cns-order-service/k8s?ref=eac2a1372ef232d2ff119ffae106e909ea456017

patches:
- path: patch-env.yml
- path: patch-volumes.yml
- path: patch-resources.yml

configMapGenerator:
- behavior: merge
  files:
  - application-prod.yml
  name: cns-order-config

images:
- name: cns-order-service
  newName: ghcr.io/akfnt/cns-order-service
  newTag: a450ed65ec14515fe8e5bfd19da76e12d2208d87

replicas:
- count: 1
  name: cns-order-service
