apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:                              # 사용자 정의 설정을 위해 깃허브의 카탈로그 서비스 저장소의 매니페스트를 베이스로 사용한다
  - github.com/akfnt/cns-catalog-service/k8s?ref=main

patches:
  - path: patch-env.yml

configMapGenerator:                     # 베이스 커스터마이제이션에 정의된 컨피그맵을 이 컨피그맵과 병합
  - behavior: merge
    files:
      - application-staging.yml
    name: cns-catalog-config            # 베이스 커스터마이제이션과 동일한 컨피그맵 이름

images:
  - name: cns-catalog-service
    newName: ghcr.io/akfnt/cns-catalog-service
    newTag: latest

replicas:
  - name: cns-catalog-service
    count: 2